### ISSUE TITLE
pypi pip needs updated to the latest version 

### ISSUE THREAD

**Issue by jlw4049** [OpusGang/awsmfunc#14]
https://pypi.org/project/awsmfunc/

Is on 1.3.1

**Comment by quietvoid** [comment]
There doesn't seem to be much interest in maintaining the pypi build.

**Comment by jlw4049** [comment]
That's fine, I thought you guys was just doing that. I can certainly just pip the github as needed

**Comment by quietvoid** [comment]
I think the issue is also that git dependencies aren't allowed there.

**Comment by jlw4049** [comment]
> I think the issue is also that git dependencies aren't allowed there

Googling around seems that it's probably more trouble then its worth. I don't mind use pip install https, works just fine
