### ISSUE TITLE
DynamicTonemap error with tone_mapping_function_s argument in version 1.3.4

### ISSUE THREAD

**Issue by patrickenfuego** [OpusGang/awsmfunc#24]
Hello. I recently started receiving an error with `DynamicTonemap` after updating the package to 1.3.4 that I was not receiving last week:

`vapoursynth.Error: Tonemap: Function does not take argument(s) named tone_mapping_function_s`

Not sure if this this is on the `awsmfunc` site or the `vs-placebo` side but rolling back to `awsmfunc` version 1.3.3 seems to fix the issue. I noticed that there have been many changes on the `vs-placebo` side, but I haven't recompiled the plugin since the last release so maybe that's my problem. 

Figured it was worth mentioning. Please let me know if there is anything else I can provide that would be helpful. Thanks for the awesome work.

**Comment by quietvoid** [comment]
It's only available if you build vs-placebo on https://github.com/Lypheo/vs-placebo/commit/369993de5817defca3e0efa98fd17bdd74e4feaa.

**Comment by patrickenfuego** [comment]
Awesome, thanks for the quick feedback @quietvoid. What do you advise I do on my end, recompile the plugin? Everything is happy at 1.3.3 (tested), but I definitely want to benefit from the latest updates.

**Comment by quietvoid** [comment]
Yes you need to build the plugin. I might update it and release a new DLL.

**Comment by patrickenfuego** [comment]
Sounds like a plan, recompiling now. Appreciate your quick response and awesome contributions! Hopefully this will help someone else in the future.
