### ISSUE TITLE
banddtct error

### ISSUE THREAD

**Issue by evafans** [OpusGang/awsmfunc#26]
import vapoursynth as vs
import awsmfunc as awf
import havsfunc as haf
from rekt import rektlvls
from awsmfunc import banddtct

core = vs.core

src = core.lsmas.LWLibavSource(r"D:\1.h264")

src = core.std.Crop (src, top=22, bottom=22, left=0, right=0)

banddtct(src)

It did ran for a while, I can see it from CPU usage.
then this error shows up:
Failed to evaluate the script:
File reading exception:
an integer is required

I used the default settings.

**Comment by quietvoid** [comment]
Can you provide the exception trace?

**Comment by evafans** [comment]
Sorry, can you tell me how to get exception trace? What should I write in VS edit?

**Comment by quietvoid** [comment]
You should be running all `awsmfunc.detect` detection scripts  in a terminal with Python directly.

**Comment by evafans** [comment]
C:\Users\Administrator>py Untitled.vpy
Running Banding detection...
Frame: 151835/151835 (68.12 fps) 100.00%
Elapsed: 2228.86 seconds (68.12 fps)
Detected frames: ....
Merged frames into zonefile: merged-banding-frames.txt
Finished detecting, output file: banding-frames.txt

When I ran it on C:\Users\Administrator, it works fine.
So I guess the problem lies with the filepath, it is unable to write files to D:\.
I'm using windows 11, maybe that's why.

**Comment by quietvoid** [comment]
You can specify the output path with `banddtct(src, output="...")`
