### ISSUE TITLE
How to use "RPU.bin"in the  MapDolbyVision

### ISSUE THREAD

**Issue by sayou112** [OpusGang/awsmfunc#28]
`src = core.ffms2.Source(r'bl.hevc',)

el = core.ffms2.Source(r'el.hevc',)
rpu=core.ffms2.Source(r'RPU.bin',)
src=awf.MapDolbyVision(src,el,rpu)`
vapoursynth.Error: Index: Can't open 'RPU.bin'
Which function should I use

**Comment by quietvoid** [comment]
`src` must be BL+EL+RPU, you don't need to specify the RPU path.

Otherwise it would be as
```python
src = awf.MapDolbyVision(src, el, rpu='RPU.bin')
```
