### ISSUE TITLE
MapDolbyVision fails when passing in rpu

### ISSUE THREAD

**Issue by jessielw** [OpusGang/awsmfunc#35]
If you attempt to pass the `EL.bin` into the function `MapDolbyVision` you'll get a failure from `vs-nlq`. 

Error:
```
vpy  [INFO]: VapourSynth Core R66
thread '<unnamed>' panicked at src\funcs\nlq.rs:97:57:
called `Option::unwrap()` on a `None` value
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Working code 
```
MapDolbyVision(bl, el)
```

Failed code
```
MapDolbyVision(bl, el, el_rpu)
```

Is passing the el_rpu required/recommended?

**Comment by quietvoid** [comment]
The error seems to be at a line where the RPU is missing NLQ info, are you passing a profile 7 RPU.

**Comment by jessielw** [comment]
You are right, I was passing a `modified` version of the RPU (offsets etc) and it was causing the error. Thanks for the information as usual!
