### ISSUE TITLE
ScreenGen blowing out highlights

### ISSUE THREAD

**Issue by CineManiac93** [OpusGang/awsmfunc#37]
Hello, I'm encountering an issue where `ScreenGen` randomly produces tone-mapped screenshots that clip the highlights. When I check the preview in **vsedit**, it shows the correct screenshot only when I don't run `ScreenGen`.

I ran a test where I had `RandomFrameNumbers` generate multiple frame numbers and produce screenshots. I then manually inserted a specific frame into each generated `screens.txt` file. Sometimes, it captured the image correctly, and other times it did not.

The reason I used the specific frame is there's a clearly noticeable highlight on a hat at the right side of the image.

Here are the screenshots:

[https://slow.pics/c/iMHp0acK](url)

- `dtm` denotes DynamicTonemap.
- `203.0` denotes target_nits.
- `xrandoms` denotes the number of **frame numbers** generated by RandomFrameNumbers **plus** the specific frame.
- The final `x2`, `x3`, etc., indicates how many **times** I generated frame numbers and took screenshots.

I also produced a heatmap of the specific frame to show the luminance.
https://ibb.co/V331Xfh

**Comment by CineManiac93** [comment]
import vapoursynth as vs
import os
core = vs.core
from awsmfunc import FrameInfo, RandomFrameNumbers, Depth, DynamicTonemap, add_hdr_measurement_props, ScreenGen
core.max_cache_size=16000

title = "Project A Part II"

path = (
r'F:\Ripped Discs\Project A Part II'
)

label0 = '88 Films'
label1 = 'Eureka'

format0 = 'UHD'
format1 = 'BD'

layer0 = 'BL'
layer1 = 'BL+FEL'
layer2 = 'HDR10'
layer3 = 'DV'

uhd = core.ffms2.Source(os.path.normpath(path) + '/' + title + "_" + label0 + "_" + format0 + ".mkv")

uhddg = core.dgdecodenv.DGSource(os.path.normpath(path) + '/' + title + "_" + label0 + "_" + format0 + ".dgi")

bd = core.ffms2.Source(os.path.normpath(path) + '/' + title + "_" + label1 + "_" + format1 + ".mkv")

bddg = core.dgdecodenv.DGSource(os.path.normpath(path) + '/' + title + "_" + label1 + "_" + format1 + ".dgi")


uhddg = core.std.Trim(uhddg, first=54)
uhd = core.std.Trim(uhd, first=54)
bddg = core.std.Trim(bddg, length=uhddg.num_frames)

#uhdcsp = core.resize.Spline64(uhd, format=vs.RGB48, dither_type='none', matrix_in_s='2020ncl')

#uhdcsp = core.std.Crop(uhdcsp, top=278, bottom=278)

bdcsp = core.resize.Spline64(bd, 3840, 2160, format=vs.RGB48, dither_type='error_diffusion', matrix_in_s='709')

max0 = 100.00

min0 = max0 / 1000

tm0 = "spline"

cr0 = 0.0

per0 = 100

gmt0 = 1

md0 = 4

#uhdmap = core.placebo.Tonemap(uhdcsp, src_csp=1, dst_csp=0, dst_min=min0, dst_max=max0, percentile=per0, contrast_recovery=cr0, dst_prim=3, metadata=md0, gamut_mapping=gmt0, tone_mapping_function_s=tm0, use_dovi=False, visualize_lut=False, show_clipping=False)

uhdmap = DynamicTonemap(uhd)


#uhdmap1 = uhdmap
#Resize
#uhdmap = core.std.SetFrameProps(uhdmap, _Transfer=vs.TRANSFER_BT709, _Primaries=vs.PRIMARIES_BT709)
uhdmap = core.std.SetFrameProps(uhdmap, _Matrix=vs.MATRIX_BT709, _Transfer=vs.TRANSFER_BT709, _Primaries=vs.PRIMARIES_BT709, _ChromaLocation=0)
bdcsp = core.std.SetFrameProps(bdcsp, _Transfer=vs.TRANSFER_BT709, _Primaries=vs.PRIMARIES_BT709, _ChromaLocation=0)

nitsstr0 = " " + str(int(max0)) + " nits"

uhdmap = FrameInfo(uhdmap, label0 + ' ' + format0 + " " + layer2 + nitsstr0)
bdout = FrameInfo(bdcsp, label1 + ' ' + format1)


uhdcrp = core.std.Crop(uhd, top=278, bottom=278)

uhd_hdrprps = add_hdr_measurement_props(uhdcrp)

uhdmap = core.akarin.Text([uhdmap, uhd_hdrprps], text='HDRMax: '+'{y.HDRMax}'+'\n'+'HDRAvg: '+'{y.HDRAvg}', prop='ass').assrender.FrameProp(style="sans-serif,20,&H00FFFFFF,&H000000FF,&H00000000,&H00000000,0,0,0,0,100,100,0,0,1,2,0,9,10,10,10,1",colorspace='Rec709')

randoms = 3


#Frame Numbers

#RandomFrameNumbers(bddg, randoms, 1000, 30000, output_file = title + "_screens.txt", ftypes_first=['B'], clips=[uhddg])

#RandomFrameNumbers(bldg, 50, 701, 2736)


#Generation

#ScreenGen([uhdmap, bdout], title + ' ' + format0 + '-' + format1 + " Screens", frame_numbers= title + '_screens.txt', prefix='frame', suffix=[ '_' + label0 + '_' + layer2 + '_tm', '_' + label1 + '_' + format1])

#ScreenGen([uhdmap], title + ' ' + format0 + " Screens", frame_numbers= title + '_screens.txt', prefix='frame', suffix=[ '_' + label0 + '_' + layer2 + '_tm' + '_' + str(max0) + '_' + str(randoms) + 'randoms_x5'])

#ScreenGen([bdout], title + ' ' + format0 + " Screens", frame_numbers= title + '_screens.txt', prefix='frame', suffix=[ '_' + label1 + '_' + format1])


#ScreenGen([uhd], title + " PQ Screenshots", frame_numbers= title + '_screens.txt', prefix='frame' , suffix = [ "_uhd_pq" ])

#Output
#bddg.set_output(0)
uhddg.set_output(1)
#bdout.set_output(2)
uhdmap.set_output(0)

**Comment by CineManiac93** [comment]
Please let me know if you need any clarifications

**Comment by quietvoid** [comment]
Since it's random there's nothing we can do about it.
There's nothing special going on in `ScreenGen`.
